apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-api
  namespace: vault
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vault-api
  template:
    metadata:
      labels:
        app: vault-api
    spec:
      containers:
        - name: vault-api
          image: vault-backend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: vault-config
          env:
            - name: JwtSettings__Secret
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: jwt-secret
            - name: MongoDB__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: mongo-connection-string
            - name: Redis__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: redis-connection-string
            - name: AzureBlobStorage__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: azure-blob-connection-string
            - name: Email__SenderPassword
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: smtp-password
---
apiVersion: v1
kind: Service
metadata:
  name: vault-api-service
  namespace: vault
spec:
  selector:
    app: vault-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
